# Generated by Django 2.1.3 on 2018-12-22 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabeledSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(default='', max_length=60, verbose_name='Labeled Aspect')),
                ('polarity', models.BooleanField(default=True, verbose_name='Labeled Polarity')),
                ('correctness', models.BooleanField(default=True, verbose_name='Correctness')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Sentence')),
                ('aspect', models.CharField(default='', max_length=60, verbose_name='Aspect')),
                ('polarity', models.BooleanField(default=True, verbose_name='Polarity')),
                ('company', models.TextField(default='', max_length=60, verbose_name='Company')),
                ('sector', models.TextField(default='', max_length=60, verbose_name='Sector')),
            ],
        ),
        migrations.AddField(
            model_name='labeledsentence',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Sentence'),
        ),
    ]
