# Generated by Django 2.1.3 on 2018-11-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Sentence')),
                ('aspect', models.CharField(max_length=60, verbose_name='Aspect')),
                ('polarity', models.BinaryField(verbose_name='Polarity')),
            ],
        ),
    ]
