# Generated by Django 2.1.3 on 2018-11-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='aspect',
            field=models.CharField(default='', max_length=60, verbose_name='Aspect'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='polarity',
            field=models.BinaryField(default=0, verbose_name='Polarity'),
        ),
    ]
