# Generated by Django 2.1.3 on 2018-11-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181126_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='polarity',
            field=models.BinaryField(null=True, verbose_name='Polarity'),
        ),
    ]
