# Generated by Django 2.1.3 on 2018-11-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20181126_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='polarity',
            field=models.BooleanField(default=True, verbose_name='Polarity'),
        ),
    ]
