# Generated by Django 2.1.3 on 2018-12-08 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0004_auto_20181126_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabeledSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(default='', max_length=60, verbose_name='Labeled Aspect')),
                ('polarity', models.BooleanField(default=True, verbose_name='Labeled Polarity')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Sentence')),
            ],
        ),
    ]
