# Generated by Django 2.1.3 on 2018-12-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_labeledsentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeledsentence',
            name='correctness',
            field=models.BooleanField(default=True, verbose_name='Correctness'),
        ),
    ]
